server:
  port: 8022

spring:
  dubbo:
    application:
      name: dubbo-provider
    base-package: com.jisuye
    registry:
      address: 127.0.0.1
      port: 2181
    protocol:
      name: dubbo

